# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f186d4033689c24a3b28f4c7e857bb66361f17c9a6d7fc09f256f7c1e729b156371e5f629def10a5e9b8d060a1652ed6f49d3fb0630feb2364c50a061dbd9966

test:
  secret_key_base: 878424967e47256f8f3619600d1971475c7479797aa6b1d53db968f84521caa726711f5fac0fb0162f13e0c63cfee45ab99e342131ab63c00135b5c53e4b282e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
